"""Compare a revised summary prompt against the summaries already in the corpus.

Gates a prompt change before the re-ingest it would trigger. Same notebooks, old
text fetched from Chroma, new text generated by the current `SUMMARY_SYSTEM`, so
the comparison is like for like.

The 2026-08-17 change has two parts with opposite risk, and the probes are chosen
to separate them: admitting problem framing and author rationale should ADD
content, while replacing the category enumeration with a criterion risks LOSING
concrete specifics — the resampling scheme and target metric above all, since
those clauses were dropped by name.

Lexical probes are a proxy for specificity, not a judgment of quality: they
detect whether a summary names a validation scheme, not whether it named the
right one. Read the side-by-side dump before trusting the percentages.

Only meaningful in the window between a prompt change and the rebuild that
regenerates the corpus — after a `--rebuild`, the stored summaries ARE the new
generation and there is nothing to compare against. That window recurs at every
prompt change.

Run: PYTHONPATH=. .venv/bin/python -m analysis.validate_summary_prompt
(needs ANTHROPIC_API_KEY; source .env first). Writes results/summary_prompt_validation.json.
"""

import json
import re
from collections import defaultdict
from pathlib import Path

import chromadb

from ingest.config import DEFAULT_SCOPE
from ingest.ingest_summaries import (
    MAX_NOTEBOOK_CHARS,
    SUMMARY_MODEL,
    _load_notebooks,
    _summarize,
)
from pipeline.config import CHROMA_PATH, NOTEBOOK_SUMMARIES

PER_COMPETITION = 5
OUT_PATH = Path("results/summary_prompt_validation.json")

# Task-diverse on purpose: a specificity regression could easily show up in
# vision but not tabular, where the vocabulary is narrower.
TARGETS = [
    "spooky-author-identification",                    # NLP (text classification)
    "jigsaw-toxic-comment-classification-challenge",   # NLP (multi-label)
    "text-normalization-challenge-english-language",   # NLP (sequence)
    "new-york-city-taxi-fare-prediction",              # tabular regression
    "nomad2018-predict-transparent-conductors",        # tabular regression (materials)
    "dogs-vs-cats-redux-kernels-edition",              # vision
    "aerial-cactus-identification",                    # vision
    "leaf-classification",                             # tabular/vision hybrid
]

PROBES = {
    # the specific regression risk: these clauses were dropped from the prompt by name
    "validation": r"\b(k-?fold|cross[- ]valid|stratif|hold ?out|out[- ]of[- ]fold|oof|"
    r"train[/ -]?(test|valid)ation? split|time[- ]series split|group k)",
    "metric": r"\b(log[- ]?loss|cross[- ]entropy|\bauc\b|roc|rmse|rmsle|\bmae\b|\bf1\b|accuracy)",
    "estimator": r"\b(xgboost|xgb|lightgbm|lgbm?|catboost|logistic regression|random forest|"
    r"\bsvm\b|naive bayes|resnet|vgg|densenet|inception|lstm|\bgru\b|bert|\bcnn\b|"
    r"gradient boosting|ridge|lasso|\bknn\b|tf-?idf)",
    "numeric_setting": r"(\b\d+\s*(epochs?|folds?|estimators?|layers?|trees?)\b|"
    r"learning[- ]rate|lr\s*=|n_estimators|batch[- ]size|dropout)",
    # what admitting rationale and problem framing was meant to add
    "rationale": r"\b(because|since|in order to|so that|to avoid|rather than|which allows|"
    r"motivat|reason)",
    "problem_framing": r"\b(predict|classif|forecast|the goal|task is|given\b|target)",
}
_COMPILED = {name: re.compile(pattern, re.I) for name, pattern in PROBES.items()}


def probe(*, text: str) -> dict:
    """Which specificity markers appear in a summary, plus its length."""
    hits: dict[str, bool | int] = {name: bool(rx.search(text)) for name, rx in _COMPILED.items()}
    hits["words"] = len(text.split())
    return hits


def sample_notebooks() -> list[tuple[int, dict]]:
    """Highest-scoring in-range notebook(s) per target competition."""
    notebooks = _load_notebooks(scope=DEFAULT_SCOPE, scored_only=False)
    by_competition: dict[str, list] = defaultdict(list)
    for kaggle_id, entry in notebooks.items():
        if (
            entry["competition_id"] in TARGETS
            and 8_000 <= entry["chars"] <= MAX_NOTEBOOK_CHARS
            and len(entry["blocks"]) >= 6
        ):
            by_competition[entry["competition_id"]].append((kaggle_id, entry))
    sampled: list[tuple[int, dict]] = []
    for competition_id in TARGETS:
        candidates = sorted(
            by_competition.get(competition_id, []),
            key=lambda pair: (pair[1]["kaggle_score"] or -1, len(pair[1]["blocks"])),
            reverse=True,
        )
        sampled.extend(candidates[:PER_COMPETITION])
    return sampled


def main() -> None:
    sampled = sample_notebooks()
    print(f"sampled {len(sampled)} notebooks across {len(TARGETS)} competitions\n", flush=True)

    collection = chromadb.PersistentClient(path=CHROMA_PATH).get_collection(
        name=NOTEBOOK_SUMMARIES
    )
    stored = collection.get(ids=[f"nb_{kid}" for kid, _ in sampled], include=["documents"])
    stored_by_id = dict(zip(stored["ids"], stored["documents"]))

    records = []
    for n, (kaggle_id, entry) in enumerate(sampled, start=1):
        old_text = stored_by_id.get(f"nb_{kaggle_id}")
        if old_text is None:
            print(f"  nb_{kaggle_id}: not in collection, skipping", flush=True)
            continue
        _, new_text = _summarize(kaggle_id=kaggle_id, entry=entry)
        records.append(
            {
                "kaggle_id": kaggle_id,
                "competition_id": entry["competition_id"],
                "old": probe(text=old_text),
                "new": probe(text=new_text),
                "old_text": old_text,
                "new_text": new_text,
            }
        )
        print(f"  {n}/{len(sampled)} nb_{kaggle_id}", flush=True)

    if not records:
        raise SystemExit("no sampled notebook had a stored summary — nothing to compare")

    print(f"\n{'probe':18} {'old':>8} {'new':>8}   delta")
    print("-" * 48)
    summary = {}
    for name in [*PROBES, "words"]:
        if name == "words":
            old_value = sum(r["old"]["words"] for r in records) / len(records)
            new_value = sum(r["new"]["words"] for r in records) / len(records)
            print(f"{'mean words':18} {old_value:8.0f} {new_value:8.0f}   {new_value - old_value:+.0f}")
        else:
            old_value = 100 * sum(r["old"][name] for r in records) / len(records)
            new_value = 100 * sum(r["new"][name] for r in records) / len(records)
            print(f"{name:18} {old_value:7.0f}% {new_value:7.0f}%   {new_value - old_value:+.0f}pp")
        summary[name] = {"old": round(old_value, 1), "new": round(new_value, 1)}

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        json.dumps(
            {
                "n": len(records),
                "summary_model": SUMMARY_MODEL,
                "per_competition": PER_COMPETITION,
                "summary": summary,
                "records": records,
            },
            indent=2,
        )
    )
    print(f"\nwrote {OUT_PATH}")

    for record in records[:3]:
        print("\n" + "=" * 92)
        print(f"{record['competition_id']} | nb {record['kaggle_id']}")
        print("--- OLD " + "-" * 84)
        print(record["old_text"])
        print("--- NEW " + "-" * 84)
        print(record["new_text"])


if __name__ == "__main__":
    main()
